run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - golint
    - gosec
    - misspell
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gofumpt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  misspell:
    locale: US
  revive:
    confidence: 0.8

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - path: cmd/
      linters:
        - gocyclo
