version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: blueprint-postgres
    environment:
      POSTGRES_DB: blueprint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # TimescaleDB for time-series data (price history, trading analytics)
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: blueprint-timescaledb
    environment:
      POSTGRES_DB: timeseries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./timescale-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c shared_preload_libraries=timescaledb

  redis:
    image: redis:7-alpine
    container_name: blueprint-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # 개발용 Redis GUI (선택사항)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: blueprint-redis-gui
    environment:
      - REDIS_HOSTS=redis:blueprint-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  timescale_data:
  redis_data:
